In [1]:
import pandas as pd
from data_transformer import DataTransformer
import tensorflow as tf
from cwgan import CWGAN
from train import Train
pd.options.display.float_format = '{:.2f}'.format

2023-04-23 22:51:44.170431: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1


In [2]:
path = './hmeq.csv'
cat_cols = ['REASON', 'JOB']
num_cols = ['LOAN', 'MORTDUE', 'VALUE', 'YOJ', 'DEROG',
            'DELINQ', 'CLAGE', 'NINQ', 'CLNO', 'DEBTINC']

target_col = 'BAD'

df = pd.read_csv(path, sep=',', index_col=False,
                    dtype={col: 'category' for col in cat_cols})
condition = True
transformer = DataTransformer(df, cat_cols, num_cols, target_col, condition)
#transformer.extractCatNumdim()
#transformer.n_numCols, transformer.cat_dims

In [3]:
df.head()

BAD  LOAN  MORTDUE     VALUE   REASON     JOB   YOJ  DEROG  DELINQ  CLAGE  \
0    1  1100 25860.00  39025.00  HomeImp   Other 10.50   0.00    0.00  94.37   
1    1  1300 70053.00  68400.00  HomeImp   Other  7.00   0.00    2.00 121.83   
2    1  1500 13500.00  16700.00  HomeImp   Other  4.00   0.00    0.00 149.47   
3    1  1500      NaN       NaN      NaN     NaN   NaN    NaN     NaN    NaN   
4    0  1700 97800.00 112000.00  HomeImp  Office  3.00   0.00    0.00  93.33   

   NINQ  CLNO  DEBTINC  
0  1.00  9.00      NaN  
1  0.00 14.00      NaN  
2  1.00 10.00      NaN  
3   NaN   NaN      NaN  
4  0.00 14.00      NaN

In [4]:
cat_dims = transformer.cat_dims
n_numCols = transformer.n_numCols

In [5]:
cat_dims, n_numCols

([2, 6], 10)

In [6]:
X_tens, y_tens, x_train = transformer.transformData()

2023-04-23 22:52:05.049394: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2023-04-23 22:52:05.050584: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2023-04-23 22:52:05.075860: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:3b:00.0 name: Quadro RTX 8000 computeCapability: 7.5
coreClock: 1.77GHz coreCount: 72 deviceMemorySize: 47.45GiB deviceMemoryBandwidth: 625.94GiB/s
2023-04-23 22:52:05.076152: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 1 with properties: 
pciBusID: 0000:af:00.0 name: Quadro RTX 8000 computeCapability: 7.5
coreClock: 1.77GHz coreCount: 72 deviceMemorySize: 47.45GiB deviceMemoryBandwidth: 625.94GiB/s
2023-04-23 22:52:05.076188: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2023-04-23 22:5

In [7]:
x_train[:10]

array([[22400.0, 52597.0, 69312.0, 2.0, 0.0, 0.0, 224.24133068, 0.0,
        12.0, 33.82410789, 'DebtCon', 'Office'],
       [10300.0, 57902.0, 74355.0, 4.0, 0.0, 0.0, 243.6309162, 1.0, 16.0,
        36.574441888, 'HomeImp', 'Other'],
       [14800.0, 43983.0, 60826.0, 4.0, 1.0, 1.0, 113.89796663, 1.0, 9.0,
        27.108081708, 'DebtCon', 'Other'],
       [11700.0, 59932.0, 80313.0, 14.0, 0.0, 0.0, 238.48646158, 0.0,
        32.0, 44.474917703, 'HomeImp', 'Office'],
       [27000.0, 45880.0, 82425.0, 21.0, 0.0, 0.0, 212.64422077, 0.0,
        27.0, 36.997793604, 'DebtCon', 'Other'],
       [10100.0, 54873.0, 73085.0, 5.0, 0.0, 1.0, 252.25289259, 1.0,
        16.0, 38.727417297, 'HomeImp', 'Other'],
       [14800.0, 30282.0, 61986.0, 7.0, 0.0, 0.0, 249.24880458, 0.0,
        16.0, 21.009280887, 'DebtCon', 'ProfExe'],
       [18800.0, 66562.0, 90325.0, 0.0, 1.0, 1.0, 112.90326219, 2.0,
        25.0, 33.162271481, 'DebtCon', 'Other'],
       [15100.0, 81461.0, 93548.0, 2.0, 0.0, 0.0, 160

In [8]:
X_tens

<tf.Tensor: shape=(5364, 18), dtype=float32, numpy=
array([[0.24013528, 0.12591106, 0.07230964, ..., 0.        , 0.        ,
        0.        ],
       [0.1037204 , 0.1392761 , 0.07825722, ..., 0.        , 0.        ,
        0.        ],
       [0.15445322, 0.10420955, 0.0623015 , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.21307778, 0.20931849, 0.10166185, ..., 0.        , 0.        ,
        0.        ],
       [0.25140923, 0.10870151, 0.06863001, ..., 0.        , 0.        ,
        0.        ],
       [0.08568207, 0.12538451, 0.06643637, ..., 0.        , 0.        ,
        0.        ]], dtype=float32)>

In [9]:
transformer.inverse_transform(X_tens)

LOAN   MORTDUE     VALUE   YOJ  DEROG  DELINQ  CLAGE  NINQ  CLNO  \
0    22400.00  52597.00  69312.00  2.00   0.00    0.00 224.24  0.00 12.00   
1    10300.00  57902.00  74355.00  4.00   0.00    0.00 243.63  1.00 16.00   
2    14800.00  43983.00  60826.00  4.00   1.00    1.00 113.90  1.00  9.00   
3    11700.00  59932.00  80313.00 14.00   0.00    0.00 238.49  0.00 32.00   
4    27000.00  45880.00  82425.00 21.00   0.00    0.00 212.64  0.00 27.00   
...       ...       ...       ...   ...    ...     ...    ...   ...   ...   
5359 11800.00  65012.00  91614.00 26.00   0.00    0.00 171.89  2.00 13.00   
5360 13400.00 102700.01 121216.00  3.00   0.00    0.00 124.56  1.00 25.00   
5361 20000.00  85704.00  94200.00  2.00   1.00    0.00 123.90  0.00 20.00   
5362 23400.00  45766.00  66192.00 26.00   0.00    0.00 284.78  2.00 32.00   
5363  8700.00  52388.00  64332.00  1.00   0.00    0.46  91.11  1.19 12.00   

      DEBTINC   REASON      JOB  
0       33.82  DebtCon   Office  
1       36.57  HomeImp    Other  
2       27.11  DebtCon    Other  
3       44.47  HomeImp   Office  
4       37.00  DebtCon    Other  
...       ...      ...      ...  
5359    42.49  HomeImp   Office  
5360    34.95  DebtCon    Other  
5361    33.78  DebtCon  ProfExe  
5362    35.94  DebtCon    Other  
5363    36.87  HomeImp    Other  

[5364 rows x 12 columns]

In [10]:
y_tens

<tf.Tensor: shape=(5364, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]], dtype=float32)>

In [22]:
cwgan = CWGAN()
generator = cwgan.make_generator(transformer)


In [11]:
cwgan = CWGAN()
batch_size = 100
epoch = 3

In [12]:
trainobject = Train(transformer, cwgan, batch_size,epoch)

In [13]:
with tf.device('/gpu:1'):
    trainobject.train()

2023-04-23 22:52:53.936858: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2023-04-23 22:52:54.562327: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7


epoch 0
epoch 1
epoch 2
epoch 3
epoch 4
epoch 5
epoch 6
epoch 7
epoch 8
epoch 9
epoch 10
epoch 11
epoch 12
epoch 13
epoch 14
epoch 15
epoch 16
epoch 17
epoch 18
epoch 19
epoch 20
epoch 21
epoch 22
epoch 23
epoch 24
epoch 25
epoch 26
epoch 27
epoch 28
epoch 29
ACC: 0.8248 AUC: 0.7476 BCE: 0.9500


In [14]:
data = trainobject.synthesise_data(100, 1)

In [15]:
data.shape

(200, 18)

In [17]:
transformer.inverse_transform(data)

LOAN   MORTDUE      VALUE   YOJ  DEROG  DELINQ  CLAGE  NINQ  CLNO  \
0    9221.46 117796.40  152346.19 -5.99   1.41    4.25 287.12 -0.84 19.77   
1   11690.47  70434.84   79562.44 -3.72   0.74    0.91  78.20  0.67 11.89   
2    6018.83  45586.79   85696.41 -1.83  -0.90    1.52  66.49 -0.10 14.22   
3   62286.82  76058.38 -150176.73 -8.94   2.35   -5.35 469.08 -2.63 22.21   
4   18340.11  30319.06  157758.69 -9.54   1.33    1.35 302.53 -2.49 19.89   
..       ...       ...        ...   ...    ...     ...    ...   ...   ...   
195 13096.12  46547.23  187779.91 11.82   2.23   -0.36 293.54  5.29  7.66   
196 23838.17 239340.33 -126172.48  9.03   3.40   -1.89 312.89 -1.59 33.11   
197 16424.70  59477.06  188784.27  6.76  -0.18    2.99   7.36  3.04 23.38   
198 19936.55 106499.28  109003.80  2.36   2.50   -0.82 321.39  1.83 13.96   
199 10500.89 128279.80   77350.27 -8.25   1.88    1.13 286.11 -1.73  9.84   

     DEBTINC   REASON     JOB  
0      42.15  HomeImp    Self  
1       7.92  DebtCon  Office  
2      54.22  DebtCon  Office  
3      40.87  HomeImp     Mgr  
4      42.75  DebtCon  Office  
..       ...      ...     ...  
195    89.82  HomeImp  Office  
196    48.92  HomeImp  Office  
197    11.57  DebtCon   Other  
198    53.30  HomeImp  Office  
199    33.20  DebtCon  Office  

[200 rows x 12 columns]

In [18]:
df.head()

BAD  LOAN  MORTDUE     VALUE   REASON     JOB   YOJ  DEROG  DELINQ  CLAGE  \
0    1  1100 25860.00  39025.00  HomeImp   Other 10.50   0.00    0.00  94.37   
1    1  1300 70053.00  68400.00  HomeImp   Other  7.00   0.00    2.00 121.83   
2    1  1500 13500.00  16700.00  HomeImp   Other  4.00   0.00    0.00 149.47   
3    1  1500      NaN       NaN      NaN     NaN   NaN    NaN     NaN    NaN   
4    0  1700 97800.00 112000.00  HomeImp  Office  3.00   0.00    0.00  93.33   

   NINQ  CLNO  DEBTINC  
0  1.00  9.00      NaN  
1  0.00 14.00      NaN  
2  1.00 10.00      NaN  
3   NaN   NaN      NaN  
4  0.00 14.00      NaN